version: '3'

services:
  chromedriver:
    image: openstax/selenium-chrome # robcherry/docker-chromedriver previously defined , testing with a more recent version/15.02.2023
    privileged: true
    restart: always
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=''
    # ports:
    #   - '4444:4444'

  selenium-side-runner:
    image: nixel2007/docker-selenium-side-runner
    # build:
    #   context: .
    volumes:
      - './sides:/sides'
      - './out:/root/out'
